# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Test on iOS 12.4
      run: xcodebuild -workspace EmojiPicker.xcworkspace -scheme EmojiPicker -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.4,name=iPhone X' test
    - name: Build & Test on iOS 13.4
      run: xcodebuild -workspace EmojiPicker.xcworkspace -scheme EmojiPicker -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.4,name=iPhone 11' test
    - name: Build & Test on iOS 14.4
      run: xcodebuild -workspace EmojiPicker.xcworkspace -scheme EmojiPicker -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 12' test
    - name: Build & Test on iOS 15.4
      run: xcodebuild -workspace EmojiPicker.xcworkspace -scheme EmojiPicker -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=15.4,name=iPhone 13' test
    - name: Build & Test on iOS 16.2
      run: xcodebuild -workspace EmojiPicker.xcworkspace -scheme EmojiPicker -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' test
